git:
  submodules: false
script:
  - ./setup.sh
  - php ./scripts/build.php
  - mkdir test
  - cd test
  - php ../poi.phar
  - php ../poi.phar blog
  - php ../poi.phar blog init ./blogA
  - php ../poi.phar blog
  - php ../poi.phar blog init ./blogB
  - php ../poi.phar blog
  - php ../poi.phar blog set ./blogA
  - php ../poi.phar blog
  - php ../poi.phar post
  - php ../poi.phar blog build
  - php ../poi.phar update
language: php
php:
  - 7.1
  - 7.2

