script:
  - composer install
  - php ./script/build.php
  - mkdir test
  - cd test
  - php ../bin/poi
  - php ../bin/poi help
  - php ../bin/poi home init ./blog
  - php ../bin/poi home init ./blog2
  - php ../bin/poi home set ./blog
  - php ../bin/poi post
  - php ../bin/poi build
  - php ../bin/poi version
  - php ../bin/poi version
  - php ../bin/poi update
  - php ../bin/poi update -d
language: php
php:
  - 7.0
