git:
  submodules: false
language: php
php:
  - 7.1
  - 7.2
script:
  - ./scripts/setup.sh
  - ./scripts/build.php
  - cd temp
  - ../poi.phar
  - ../poi.phar blog
  - ../poi.phar blog init ./blogA
  - ../poi.phar blog
  - ../poi.phar blog init ./blogB
  - ../poi.phar blog
  - ../poi.phar blog set ./blogA
  - ../poi.phar blog
  - ../poi.phar post
  - ../poi.phar blog build

