script:
  - ./setup.sh
  - php ./scripts/build.php
  - mkdir test
  - cd test
  - php ../poi.phar
  - php ../poi.phar help
  - php ../poi.phar home init ./blog
  - php ../poi.phar home init ./blog2
  - php ../poi.phar home set ./blog
  - php ../poi.phar post
  - php ../poi.phar build
  - php ../poi.phar version
  - php ../poi.phar update
  - php ../poi.phar update -d
language: php
php:
  - 7.1
  - 7.2
